### ISSUE TITLE
テストケース

### ISSUE THREAD

**Issue by corvvs** [corvvs/libftdd#1]
## Part 1

- [x] `memset`
- [ ] `bzero`
- [x] `memcpy`
- [x] `memmove`
- [x] `memcmp`
- [x] `memchr`
- [x] `isalpha`
- [x] `isdigit`
- [x] `isalnum`
- [x] `isprint`
- [x] `isascii`
- [x] `toupper`
- [x] `tolower`
- [x] `strlen`
- [x] `strchr`
- [x] `strrchr`
- [ ] `strnstr`
- [x] `strncmp`
- [ ] `strlcat`
- [ ] `strlcpy`
- [ ] `strdup`
- [ ] `calloc`
- [x] `atoi`

## Part 2

- [ ] `ft_putchar_fd`
- [ ] `ft_putstr_fd`
- [ ] `ft_putendl_fd`
- [ ] `ft_putnbr_fd`
- [x] `ft_strjoin`
- [ ] `ft_strtrim`
- [ ] `ft_substr`
- [ ] `ft_split`
- [ ] `ft_itoa`
- [ ] `ft_strmapi`
- [ ] `ft_striteri`

## Bonus

- [ ] `ft_lstnew`
- [ ] `ft_lstsize`
- [ ] `ft_lstlast`
- [ ] `ft_lstdelone`
- [ ] `ft_lstclear`
- [ ] `ft_lstiter`
- [ ] `ft_lstmap`
